CREATE DATABASE QLKhachhang_BuiGiaTien;
go
USE QLKhachhang_BuiGiaTien;

CREATE TABLE KHACHHANG (
	MAKH VARCHAR(10) PRIMARY KEY
	,HOTEN NVARCHAR(50)
	,DCHI NVARCHAR(250)
	,SODT VARCHAR(50)
	,NGSINH DATE
);

CREATE TABLE SANPHAM (
	MASP VARCHAR(50) PRIMARY KEY
	,TENSP NVARCHAR(50)
	,DVT NVARCHAR(50)
	,NUOCSX NVARCHAR(50)
	,DONGIA INT
);

CREATE TABLE HOADON (
	SOHD INT PRIMARY KEY
	,NGAYHD DATE
	,MAKH VARCHAR(10) FOREIGN KEY REFERENCES KHACHHANG(MAKH)
);

CREATE TABLE CTHOADON (
	SOHD INT FOREIGN KEY REFERENCES HOADON(SOHD)
	,MASP VARCHAR(50) FOREIGN KEY REFERENCES SANPHAM(MASP)
);

-- nhap du lieu:
