CREATE DATABASE QLKhachhang_BuiGiaTien;
go
USE QLKhachhang_BuiGiaTien;

CREATE TABLE KHACHHANG (
	MAKH VARCHAR(10) PRIMARY KEY
	,HOTEN NVARCHAR(50)
	,DCHI NVARCHAR(250)
	,SODT VARCHAR(50)
	,NGSINH DATE
);

CREATE TABLE SANPHAM (
	MASP VARCHAR(50) PRIMARY KEY
	,TENSP NVARCHAR(50)
	,DVT NVARCHAR(50)
	,NUOCSX NVARCHAR(50)
	,DONGIA INT
);

