/* bai thuc hanh 3 */
/*** XU LY CHUOI VA NGAY GIO ***/
-- #1:
SELECT NGAYTD, A.TENCLB AS TENCLB1, B.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU TD
	JOIN CAULACBO A ON A.MACLB = TD.MACLB1
	JOIN CAULACBO B ON B.MACLB = TD.MACLB2
WHERE KETQUA = N'0-0'
AND MONTH(NGAYTD) = 3;

-- #2:
SELECT SO AS MASO, HOTEN, NGAYSINH
FROM CAUTHU
WHERE HOTEN LIKE N'%Công%';

-- #3:
SELECT SO AS MASO, HOTEN, NGAYSINH
FROM CAUTHU
WHERE HOTEN NOT LIKE N'Nguyễn%';

-- #4:
SELECT MAHLV, TENHLV, NGAYSINH, DIACHI, (YEAR(GETDATE()) - YEAR(NGAYSINH)) AS TUOI
FROM HUANLUYENVIEN
WHERE YEAR(GETDATE()) - YEAR(NGAYSINH) BETWEEN 35 AND 40;

-- #5:
SELECT TENCLB FROM CAULACBO CLB
	JOIN HLV_CLB HC ON HC.MACLB = CLB.MACLB
	JOIN HUANLUYENVIEN HLV ON HC.MAHLV = HLV.MAHLV
WHERE CONVERT(varchar, NGAYSINH, 103) = '20/08/2019';

-- SELECT CONVERT(varchar, NGAYSINH, 103) FROM HUANLUYENVIEN;

-- #6:
WITH BESTCLB AS
(
	SELECT TOP 1 MACLB, SUM(CAST(LEFT(HIEUSO, 1) AS int)) AS SOBANTHANG FROM BANGXH
	WHERE NAM = 2009
		AND VONG <= 3
	GROUP BY MACLB
	ORDER BY SOBANTHANG DESC
)
SELECT TENCLB, T.TENTINH
FROM CAULACBO CLB
	JOIN TINH T ON T.MATINH = CLB.MATINH
	JOIN BESTCLB BC ON BC.MACLB = CLB.MACLB;

/*** TRUY VAN CON ***/
-- #1:
WITH NUOCNGOAI AS (
	SELECT MACLB, COUNT(*) AS SOLUONGCTNN FROM CAUTHU
	WHERE MAQG != 'VN'
	GROUP BY MACLB
	)
SELECT CLB.MACLB, CLB.TENCLB, S.TENSAN, S.DIACHI, SOLUONGCTNN
FROM CAULACBO CLB
	JOIN SANVD S ON S.MASAN = CLB.MASAN
	JOIN NUOCNGOAI CT ON CT.MACLB = CLB.MACLB;

-- #2:
WITH TOPCLB AS
(
	SELECT TOP 1 MACLB, SUM(CAST(LEFT(HIEUSO, 1) AS smallint) - CAST(RIGHT(HIEUSO, 1) AS smallint)) AS TONG
	FROM BANGXH
	GROUP BY MACLB
	ORDER BY TONG DESC
)
SELECT TENCLB, TENTINH
FROM CAULACBO C
	JOIN TINH T ON T.MATINH = C.MATINH
	JOIN TOPCLB ON TOPCLB.MACLB = C.MACLB;

-- #3:
DECLARE @WEEKEST VARCHAR(5)
SET @WEEKEST =
(
SELECT TOP 1 MACLB FROM BANGXH
WHERE VONG = 3
	AND NAM = 2009
ORDER BY HANG DESC
)
SELECT NGAYTD, TENSAN, C1.TENCLB AS TENCLB1, C2.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU TD
	JOIN SANVD S ON S.MASAN = TD.MASAN
	JOIN CAULACBO C1 ON C1.MACLB = TD.MACLB1
	JOIN CAULACBO C2 ON C2.MACLB = TD.MACLB2
WHERE MACLB1 = @WEEKEST
	OR MACLB2 = @WEEKEST;
GO

-- #4:
SELECT MACLB, TENCLB FROM CAULACBO
WHERE MACLB IN (
	SELECT MACLB FROM BANGXH
	WHERE NAM = 2009
	GROUP BY MACLB
	HAVING MAX(SOTRAN) + 1 = (
		SELECT COUNT(DISTINCT(MACLB)) FROM BANGXH	--> số lượng câu lạc bộ thi đấu năm 2009
		WHERE NAM = 2009
		)
	);

-- #5:
WITH SOTRAN AS (
	SELECT MACLB1 AS MACLB, COUNT(DISTINCT MACLB2) AS TONG			--> tổng số trận khi ở đội 1 và thi đấu trên sân nhà.
	FROM TRANDAU TD JOIN CAULACBO CLB ON TD.MACLB1 = CLB.MACLB
	WHERE NAM = 2009 AND TD.MASAN = CLB.MASAN
	GROUP BY MACLB1
	UNION ALL
	SELECT MACLB2 AS MACLB, COUNT(DISTINCT MACLB1) AS TONG			--> tổng số trận khi ở đội 2 và thi đấu trên sân nhà.
	FROM TRANDAU TD JOIN CAULACBO CLB ON TD.MACLB2 = CLB.MACLB
	WHERE NAM = 2009 AND TD.MASAN = CLB.MASAN
	GROUP BY MACLB2
	)
	SELECT MACLB, TENCLB											-- => gọi kết quả cuối.
	FROM CAULACBO
	WHERE MACLB IN (
		SELECT MACLB FROM SOTRAN									--> gọi đội có tổng số trận trên sân nhà + 1 = tổng số đội.
		GROUP BY MACLB
		HAVING SUM(TONG) + 1 = (
			SELECT COUNT(DISTINCT(MACLB)) FROM BANGXH				--> số lượng câu lạc bộ thi đấu năm 2009
			WHERE NAM = 2009 )
		);

/*** BAI TAP VE RULE ***/
-- #1:
ALTER TABLE CAUTHU
ADD CHECK (VITRI IN (N'Thủ môn', N'Tiền đạo', N'Tiền vệ', N'Trung vệ', N'Hậu vệ'));

-- #2:
ALTER TABLE HLV_CLB
ADD CHECK (VAITRO IN (N'HLV Chính', N'HLV Phụ', N'HLV Thể lực', N'HLV Thủ môn'));

-- #3:
ALTER TABLE CAUTHU
ADD CHECK (YEAR(GETDATE()) - YEAR(NGAYSINH) >= 18);

-- #4:
ALTER TABLE TRANDAU
ADD CONSTRAINT CK_TRANDAU_KETQUA_THANG_THUA 
	CHECK (KETQUA LIKE "[0-9]-[0-9]"	--> DẠNG SỐ TRỪ SỐ
	AND CAST(LEFT(KETQUA,1) AS smallint) - CAST(RIGHT(KETQUA,1) AS smallint) > 0); --> CHỈ SỐ THẰNG - THUA > 0

/*** BÀI TẬP VỀ VIEW ***/
-- #1:
GO
CREATE VIEW cauthu_brazil AS
SELECT HOTEN, NGAYSINH, DIACHI, VITRI
FROM CAUTHU
WHERE MAQG = 'BRA';
GO
SELECT * FROM cauthu_brazil;
GO

-- #2:
CREATE VIEW KETQUA_VONG3_2009 AS
SELECT MATRAN, NGAYTD, S.TENSAN, A.TENCLB AS TENCLB1, B.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU
	JOIN SANVD S ON S.MASAN = TRANDAU.MASAN
	JOIN CAULACBO A ON A.MACLB = TRANDAU.MACLB1
	JOIN CAULACBO B ON B.MACLB = TRANDAU.MACLB2
WHERE VONG = 3 AND NAM = 2009;
GO
SELECT * FROM KETQUA_VONG3_2009;
GO

-- #3:
CREATE VIEW HLV_VIETNAM AS
SELECT H.MAHLV, TENHLV, NGAYSINH, DIACHI, VAITRO, C.TENCLB
FROM HUANLUYENVIEN H
	JOIN HLV_CLB HC ON HC.MAHLV = H.MAHLV
	JOIN CAULACBO C ON C.MACLB = HC.MACLB
WHERE MAQG = 'VN';
GO
SELECT * FROM HLV_VIETNAM;
GO

-- #4:
CREATE VIEW SOLUONG_CAUTHU_NUOCNGOAI AS
SELECT MACLB, COUNT(*) AS SOLUONG
FROM CAUTHU
WHERE MAQG != 'VN'
GROUP BY MACLB;
GO
SELECT C.MACLB, TENCLB, TENSAN, DIACHI, SOLUONG AS SOLUONG_CAUTHU_NUOCNGOAI
FROM SOLUONG_CAUTHU_NUOCNGOAI NN
	JOIN CAULACBO C ON C.MACLB = NN.MACLB
	JOIN SANVD S ON S.MASAN = C.MASAN
WHERE NN.SOLUONG > 2;
GO

-- #5:
CREATE VIEW SOLUONG_TIENDAO AS
SELECT TENTINH, COUNT(CT.MACT) AS SOLUONG_TIENDAO
FROM TINH T
	JOIN CAULACBO C ON C.MATINH = T.MATINH
	JOIN CAUTHU CT ON CT.MACLB = C.MACLB
WHERE VITRI = N'Tiền đạo'
GROUP BY TENTINH;
GO 
SELECT * FROM SOLUONG_TIENDAO;
GO

-- #6:
CREATE VIEW WINNER_VONG3_2009 AS
SELECT TENCLB, TENTINH
FROM BANGXH B
	JOIN CAULACBO C ON C.MACLB = B.MACLB
	JOIN TINH T ON T.MATINH = C.MATINH
WHERE NAM = 2009 AND VONG = 3
	AND HANG = 1;
GO 
SELECT * FROM WINNER_VONG3_2009;
GO

-- #7:
CREATE VIEW HLV_HOATDONG_KHONGSDT AS
SELECT TENHLV
FROM HUANLUYENVIEN H
	JOIN HLV_CLB HC ON HC.MAHLV = H.MAHLV
WHERE DIENTHOAI = NULL;
GO
SELECT * FROM HLV_HOATDONG_KHONGSDT;
GO

-- #8:
CREATE VIEW HLV_KOHOATDONG AS
SELECT MAHLV, TENHLV, MAQG
FROM HUANLUYENVIEN H
WHERE MAHLV NOT IN (SELECT MAHLV
					FROM HLV_CLB);
GO
SELECT TENHLV FROM HLV_KOHOATDONG
WHERE MAQG = 'VN';
GO

-- #9:
CREATE VIEW KETQUA_TRANDAU AS
SELECT MACLB1, MACLB2, NAM, VONG, LEFT(KETQUA, 1) AS SOBANTHANG, RIGHT(KETQUA, 1) AS SOBANTHUA
FROM TRANDAU;
GO
SELECT * FROM KETQUA_TRANDAU;
GO

-- #10:
CREATE VIEW KETQUA_SANNHA AS
SELECT MACLB1 AS MACLB, NAM, VONG, LEFT(KETQUA, 1) AS SOBANTHANG, RIGHT(KETQUA, 1) AS SOBANTHUA
FROM TRANDAU T
	JOIN CAULACBO C ON C.MASAN = T.MASAN AND C.MACLB = T.MACLB1;
GO
SELECT * FROM KETQUA_SANNHA;
GO

-- #11:
CREATE VIEW KETQUA_SANKHACH AS
SELECT MACLB1 AS MACLB, NAM, VONG, LEFT(KETQUA, 1) AS SOBANTHANG, RIGHT(KETQUA, 1) AS SOBANTHUA
FROM TRANDAU T
	JOIN CAULACBO C ON C.MASAN = T.MASAN AND C.MACLB = T.MACLB2;
GO
SELECT * FROM KETQUA_SANKHACH;
GO

-- #12:
--> CLB hang 1 het vong 3
CREATE VIEW TOP_CLB_HETVONG3 AS
SELECT TOP 1 B.MACLB, TENCLB, SUM(HANG) AS TONG_HANG 
FROM BANGXH B JOIN CAULACBO C ON C.MACLB = B.MACLB
WHERE NAM = 2009 AND VONG <= 3
GROUP BY B.MACLB, TENCLB
ORDER BY TONG_HANG;
GO
--> DANH SÁCH TRẬN ĐẤU CÓ HẠNG 1 HẾT VÒNG 3 GÓP MẶT
SELECT NGAYTD, TENSAN, A.TENCLB AS TENCLB1, B.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU T
	JOIN SANVD S ON S.MASAN = T.MASAN
	JOIN TOP_CLB_HETVONG3 TT ON TT.MACLB = T.MACLB1
							OR TT.MACLB = T.MACLB2
	----------- TÊN CLB TRÁI, PHẢI ------------
	JOIN CAULACBO A ON A.MACLB = T.MACLB1
	JOIN CAULACBO B ON B.MACLB = T.MACLB2;
GO

-- #13:
--> CLB TỆ NHẤT VÒNG 3
CREATE VIEW WORST_CLB_VONG3 AS
SELECT TOP 1 B.MACLB, TENCLB
FROM BANGXH B JOIN CAULACBO C ON C.MACLB = B.MACLB
ORDER BY HANG DESC
GO
--> DANH SÁCH TRẬN ĐẤU CÓ HẠNG 1-NGƯỢC VÒNG 3 GÓP MẶT
SELECT NGAYTD, TENSAN, A.TENCLB AS TENCLB1, B.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU T
	JOIN SANVD S ON S.MASAN = T.MASAN
	JOIN WORST_CLB_VONG3 TT ON TT.MACLB = T.MACLB1
							OR TT.MACLB = T.MACLB2
	----------- TÊN CLB TRÁI, PHẢI ------------
	JOIN CAULACBO A ON A.MACLB = T.MACLB1
	JOIN CAULACBO B ON B.MACLB = T.MACLB2;
GO