/* bai thuc hanh 3 */
/*** XU LY CHUOI VA NGAY GIO ***/
-- #1:
SELECT NGAYTD, A.TENCLB AS TENCLB1, B.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU TD
	JOIN CAULACBO A ON A.MACLB = TD.MACLB1
	JOIN CAULACBO B ON B.MACLB = TD.MACLB2
WHERE KETQUA = N'0-0'
AND MONTH(NGAYTD) = 3;

-- #2:
SELECT SO AS MASO, HOTEN, NGAYSINH
FROM CAUTHU
WHERE HOTEN LIKE N'%Công%';

-- #3:
SELECT SO AS MASO, HOTEN, NGAYSINH
FROM CAUTHU
WHERE HOTEN NOT LIKE N'Nguyễn%';

-- #4:
SELECT MAHLV, TENHLV, NGAYSINH, DIACHI, (YEAR(GETDATE()) - YEAR(NGAYSINH)) AS TUOI
FROM HUANLUYENVIEN
WHERE YEAR(GETDATE()) - YEAR(NGAYSINH) BETWEEN 35 AND 40;

-- #5:
SELECT TENCLB FROM CAULACBO CLB
	JOIN HLV_CLB HC ON HC.MACLB = CLB.MACLB
	JOIN HUANLUYENVIEN HLV ON HC.MAHLV = HLV.MAHLV
WHERE CONVERT(varchar, NGAYSINH, 103) = '20/08/2019';

-- SELECT CONVERT(varchar, NGAYSINH, 103) FROM HUANLUYENVIEN;

-- #6:
WITH BESTCLB AS
(
	SELECT TOP 1 MACLB, SUM(CAST(LEFT(HIEUSO, 1) AS int)) AS SOBANTHANG FROM BANGXH
	WHERE NAM = 2009
		AND VONG <= 3
	GROUP BY MACLB
	ORDER BY SOBANTHANG DESC
)
SELECT TENCLB, T.TENTINH
FROM CAULACBO CLB
	JOIN TINH T ON T.MATINH = CLB.MATINH
	JOIN BESTCLB BC ON BC.MACLB = CLB.MACLB;

/*** TRUY VAN CON ***/
-- #1:
SELECT CLB.MACLB, CLB.TENCLB, S.TENSAN, S.DIACHI, CT.COUNT(*) AS SOLUONGCTNN
FROM CAULACBO CLB
	JOIN SANVD S ON S.MASAN = CLB.MASAN
	JOIN CAUTHU CT ON CT.MACLB = CLB.MACLB
GROUP BY CLB.MACLB

