/* bai thuc hanh 3 */
/*** XU LY CHUOI VA NGAY GIO ***/
-- #1:
SELECT NGAYTD, A.TENCLB AS TENCLB1, B.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU TD
	JOIN CAULACBO A ON A.MACLB = TD.MACLB1
	JOIN CAULACBO B ON B.MACLB = TD.MACLB2
WHERE KETQUA = N'0-0'
AND MONTH(NGAYTD) = 3;

-- #2:
SELECT SO AS MASO, HOTEN, NGAYSINH
FROM CAUTHU
WHERE HOTEN LIKE N'%Công%';

-- #3:
SELECT SO AS MASO, HOTEN, NGAYSINH
FROM CAUTHU
WHERE HOTEN NOT LIKE N'Nguyễn%';

-- #4:
SELECT MAHLV, TENHLV, NGAYSINH, DIACHI, (YEAR(GETDATE()) - YEAR(NGAYSINH)) AS TUOI
FROM HUANLUYENVIEN
WHERE YEAR(GETDATE()) - YEAR(NGAYSINH) BETWEEN 35 AND 40;

-- #5:
SELECT TENCLB FROM CAULACBO CLB
	JOIN HLV_CLB HC ON HC.MACLB = CLB.MACLB
	JOIN HUANLUYENVIEN HLV ON HC.MAHLV = HLV.MAHLV
WHERE CONVERT(varchar, NGAYSINH, 103) = '20/08/2019';

-- SELECT CONVERT(varchar, NGAYSINH, 103) FROM HUANLUYENVIEN;

-- #6:
WITH BESTCLB AS
(
	SELECT TOP 1 MACLB, SUM(CAST(LEFT(HIEUSO, 1) AS int)) AS SOBANTHANG FROM BANGXH
	WHERE NAM = 2009
		AND VONG <= 3
	GROUP BY MACLB
	ORDER BY SOBANTHANG DESC
)
SELECT TENCLB, T.TENTINH
FROM CAULACBO CLB
	JOIN TINH T ON T.MATINH = CLB.MATINH
	JOIN BESTCLB BC ON BC.MACLB = CLB.MACLB;

/*** TRUY VAN CON ***/
-- #1:
WITH NUOCNGOAI AS (
	SELECT MACLB, COUNT(*) AS SOLUONGCTNN FROM CAUTHU
	WHERE MAQG != 'VN'
	GROUP BY MACLB
	)
SELECT CLB.MACLB, CLB.TENCLB, S.TENSAN, S.DIACHI, SOLUONGCTNN
FROM CAULACBO CLB
	JOIN SANVD S ON S.MASAN = CLB.MASAN
	JOIN NUOCNGOAI CT ON CT.MACLB = CLB.MACLB;

-- #2:
WITH TOPCLB AS
(
	SELECT TOP 1 MACLB, SUM(CAST(LEFT(HIEUSO, 1) AS smallint) - CAST(RIGHT(HIEUSO, 1) AS smallint)) AS TONG
	FROM BANGXH
	GROUP BY MACLB
	ORDER BY TONG DESC
)
SELECT TENCLB, TENTINH
FROM CAULACBO C
	JOIN TINH T ON T.MATINH = C.MATINH
	JOIN TOPCLB ON TOPCLB.MACLB = C.MACLB;

-- #3:
DECLARE @WEEKEST VARCHAR(5)
SET @WEEKEST =
(
SELECT TOP 1 MACLB FROM BANGXH
WHERE VONG = 3
	AND NAM = 2009
ORDER BY HANG DESC
)
SELECT NGAYTD, TENSAN, C1.TENCLB AS TENCLB1, C2.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU TD
	JOIN SANVD S ON S.MASAN = TD.MASAN
	JOIN CAULACBO C1 ON C1.MACLB = TD.MACLB1
	JOIN CAULACBO C2 ON C2.MACLB = TD.MACLB2
WHERE MACLB1 = @WEEKEST
	OR MACLB2 = @WEEKEST;
GO

-- #4:
SELECT MACLB, TENCLB FROM CAULACBO
WHERE MACLB IN (
	SELECT MACLB FROM BANGXH
	WHERE NAM = 2009
	GROUP BY MACLB
	HAVING MAX(SOTRAN) + 1 = (
		SELECT COUNT(DISTINCT(MACLB)) FROM BANGXH	--> số lượng câu lạc bộ thi đấu năm 2009
		WHERE NAM = 2009
		)
	);

-- #5:
WITH SOTRAN AS (
	SELECT MACLB1 AS MACLB, COUNT(DISTINCT MACLB2) AS TONG			--> tổng số trận khi ở đội 1 và thi đấu trên sân nhà.
	FROM TRANDAU TD JOIN CAULACBO CLB ON TD.MACLB1 = CLB.MACLB
	WHERE NAM = 2009 AND TD.MASAN = CLB.MASAN
	GROUP BY MACLB1
	UNION ALL
	SELECT MACLB2 AS MACLB, COUNT(DISTINCT MACLB1) AS TONG			--> tổng số trận khi ở đội 2 và thi đấu trên sân nhà.
	FROM TRANDAU TD JOIN CAULACBO CLB ON TD.MACLB2 = CLB.MACLB
	WHERE NAM = 2009 AND TD.MASAN = CLB.MASAN
	GROUP BY MACLB2
	)
	SELECT MACLB, TENCLB											-- => gọi kết quả cuối.
	FROM CAULACBO
	WHERE MACLB IN (
		SELECT MACLB FROM SOTRAN									--> gọi đội có tổng số trận trên sân nhà + 1 = tổng số đội.
		GROUP BY MACLB
		HAVING SUM(TONG) + 1 = (
			SELECT COUNT(DISTINCT(MACLB)) FROM BANGXH				--> số lượng câu lạc bộ thi đấu năm 2009
			WHERE NAM = 2009 )
		);

/*** BAI TAP VE RULE ***/
-- #1:
